---
title: "Exercise 1"
author: "Karissa Dysart, Erin Williams, Karla Oropeza, Alan Nurcahyo"
date: "6/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## part 1
```{r}
library(rvest)
url <- 'http://ipaidabribe.com/reports/paid'
bribes <- read_html(url)
```

##part 2
```{r}
amounts <- bribes %>%
  html_nodes('.paid-amount span') %>%
  html_text()

amounts <- gsub("Paid INR | |\r|\n|,", "", amounts) # remove text, white space, and commas
amounts <- as.numeric(amounts) # convert to numeric
```

# part 3
```{r}
transaction <- bribes %>%
  html_nodes('.transaction a') %>%
  html_text()

dept <- bribes %>%
  html_nodes('.name a') %>%
  html_text()
```
# part 4
```{r}
# scrape_bribe function
scrape_bribe <- function(url){
bribes <- read_html(url)
# variables that we're interested in
amounts <- html_text(html_nodes(bribes, ".paid-amount span"))
amounts <- as.numeric(gsub("Paid INR | |\r|\n|,", "", amounts))
transaction <- html_text(html_nodes(bribes, ".transaction a"))
dept <- html_text(html_nodes(bribes, ".name a"))
# putting together into a data frame
df <- data.frame(
  amounts = amounts,
  transaction = transaction,
  dept = dept,
  stringsAsFactors=F)
return(df)
}

#create an empty list called bribes with the list() function
bribes <- list()
bribes[[1]] <- scrape_bribe(url)
str(bribes)

## base url
base_url <- "http://ipaidabribe.com/reports/paid?page="

#create sequence
pages <- seq(0,40, by =10)
pages
## making a loop
for (i in 2:length(pages)){
# informative message about progress of loop
  message(i, '/', length(pages))
# prepare URL
  url <- paste(base_url, pages[i], sep="")
# scrape website
  bribes[[i]] <- scrape_bribe(url)
# wait a couple of seconds between URL calls
  Sys.sleep(2)
}

#convert the list of data frames into a single data frame that we can work with
bribes <- do.call(rbind, bribes)
head(bribes)
str(bribes)
```


# part 5
```{r}
#First, what is the most common transaction during which a bribe was paid? 
table(bribes$transaction)%>%
  sort()
#Second, what was the average bribe payment? (use the summary() function or the mean() function)
mean(bribes$amounts)

#Finally, which department was responsible for the most transactions during which a bribe occurred?
library(tidyverse)
bribes %>%
  group_by(dept) %>%
  tally() %>%
  arrange(desc(n))
```

